# Generated by Django 4.2.16 on 2024-09-03 19:40

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(upload_to='audio/', validators=[songs.models.validate_audio_file]),
        ),
    ]
