# Generated by Django 4.2.16 on 2024-09-03 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('songs', '0002_alter_songs_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artists'),
        ),
    ]
