# Generated by Django 4.2.16 on 2024-09-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_songs_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='played_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
