# Generated by Django 4.2.16 on 2024-09-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albuns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='isSingle',
            field=models.BooleanField(default=False),
        ),
    ]
